apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      name: ui
    - port: 4317
      protocol: TCP
      name: grpc
    - port: 4318
      protocol: TCP
      name: http
  selector:
    run: grafana
