apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  containers:
  - name: grafana
    image: grafana/otel-lgtm
    ports:
      - containerPort: 3000
      - containerPort: 4317
      - containerPort: 4318
